### ISSUE TITLE
Can VAC detect python cheats .py ? or VAC cant do it?

### ISSUE THREAD

**Issue by nikita-tarasov3** [kadeeq/Python-CSGO-Cheat#10]
Can VAC detect python cheats .py ? or VAC cant do it?

**Comment by kadeeq** [comment]
https://guidedhacking.com/threads/how-to-bypass-vac-valve-anti-cheat-info.8125/
TLDR: Yes but as this cheat is fairly small it probably wont be detected until it becomes more popular. Some features like silentaim with a very high fov  might cause you to get untrusted tho. You can make it more undetected by adding junkcode or smth. if you want. VAC is very bad tho so unless you just copy paste a very popular public cheat and dont know what youre doing you wont get vacced
