### ISSUE TITLE
Работает на Faceit?

### ISSUE THREAD

**Issue by trigan2** [kadeeq/Python-CSGO-Cheat#3]
Работает на Faceit?
Powered by Faceit?
_Originally posted by @trigan2 in https://github.com/kadeeq/Python-CSGO-Cheat/issues/2#issuecomment-753963686_

**Comment by kadeeq** [comment]
Sadly it doesnt work on faceit atm ( i may be doing a fix in te future but as their ac is actually good theres not much i can do right now)
