### ISSUE TITLE
目前还能用吗？？ 会不会被VAC？

### ISSUE THREAD

**Issue by SuHaoXD** [kadeeq/Python-CSGO-Cheat#4]

**Comment by SuHaoXD** [comment]
pymem.exception.MemoryWriteError: Could not write memory at: 3620, length: 0 - GetLastError: 998  
why?

**Comment by SuHaoXD** [comment]
pymem.exception.WinAPIError: Windows api error, error_code: 998

It doesn't work！

**Comment by kadeeq** [comment]
Seems to be an issue with the new update 
gonna be working again soon

**Comment by kadeeq** [comment]
Working again
