### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by hujihan** [kadeeq/Python-CSGO-Cheat#5]
I input in CMD“ pythonProjectLarry.py ”It didn't work
![QQ图片20210121202406](https://user-images.githubusercontent.com/46958243/105350787-9296eb00-5be3-11eb-8989-cffcb2b25be7.png)And is that normal？

**Comment by kadeeq** [comment]
Im sorry man I still had the wrong name in the TUTORIAL.txt file.
You do need to put a space between python and the file awell.
And yes this is complete normal, it just says that you have all the needed modules installed.
BTW you dont need to do pip install every time you start the cheat. Just do it the first time then everything should work

**Comment by hujihan** [comment]
thank you!!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kadeeq"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 下午3:27
收件人: "kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;; 
抄送: "miku_Crypton"<hujihan0353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kadeeq/Python-CSGO-Cheat] unavailable (#5)





 
对不起，我在TUTORIAL.txt文件中的名称仍然错误。
 您确实需要在python和文件之间放置一个空格。
 是的，这完全正常，它只是说您已安装了所有需要的模块。
 顺便说一句，您不需要在每次开始作弊时进行pip安装。第一次做就可以了
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by hujihan** [comment]
Hello, I tried your method, but still no response
Is that right?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kadeeq"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 下午3:27
收件人: "kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;; 
抄送: "miku_Crypton"<hujihan0353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kadeeq/Python-CSGO-Cheat] unavailable (#5)





 
Im sorry man I still had the wrong name in the TUTORIAL.txt file.
 You do need to put a space between python and the file awell.
 And yes this is complete normal, it just says that you have all the needed modules installed.
 BTW you dont need to do pip install every time you start the cheat. Just do it the first time then everything should work
