### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by hujihan** [kadeeq/Python-CSGO-Cheat#6]
Hello, I tried your method, but still no response
![QQ图片20210122154515](https://user-images.githubusercontent.com/46958243/105462809-17871080-5c87-11eb-93ac-f847d920bc75.png)
Is that right?

**Comment by kadeeq** [comment]
Could you show me a screenshot of the "dir" command in the powershell in this dictionary. Maybe the file is named different for you.

**Comment by hujihan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kadeeq/Python-CSGO-Cheat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 下午3:58
收件人:&nbsp;"kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;;
抄送:&nbsp;"miku_Crypton"<hujihan0353@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)





 
Could you show me a screenshot of the "dir" command in the powershell in this dictionary. Maybe the file is named different for you.

**Comment by kadeeq** [comment]
?

**Comment by kadeeq** [comment]
i meant directory not dictionary

**Comment by hujihan** [comment]
This is the directory。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kadeeq"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 下午4:03
收件人: "kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;; 
抄送: "miku_Crypton"<hujihan0353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)





 
i meant directory not dictionary

**Comment by kadeeq** [comment]
wait
what is your os

**Comment by kadeeq** [comment]
![grafik](https://user-images.githubusercontent.com/62156037/105464043-3a1e2700-5c91-11eb-84a1-8625cb25b043.png)

**Comment by kadeeq** [comment]
this

**Comment by hujihan** [comment]
Windows10




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kadeeq/Python-CSGO-Cheat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 下午4:07
收件人:&nbsp;"kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;;
抄送:&nbsp;"miku_Crypton"<hujihan0353@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)





 
wait
 what is your os

**Comment by kadeeq** [comment]
ok good

**Comment by kadeeq** [comment]
mind sharing the screenshot otheriwse i cant help you

**Comment by hujihan** [comment]
What screenshot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kadeeq"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 下午4:17
收件人: "kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;; 
抄送: "miku_Crypton"<hujihan0353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)





 
mind sharing the screenshot otheriwse i cant help you

**Comment by hujihan** [comment]
What screenshot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kadeeq/Python-CSGO-Cheat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 下午4:17
收件人:&nbsp;"kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;;
抄送:&nbsp;"miku_Crypton"<hujihan0353@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)





 
mind sharing the screenshot otheriwse i cant help you

**Comment by hujihan** [comment]
Windows10




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kadeeq"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 下午4:07
收件人: "kadeeq/Python-CSGO-Cheat"<Python-CSGO-Cheat@noreply.github.com&gt;; 
抄送: "miku_Crypton"<hujihan0353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kadeeq/Python-CSGO-Cheat] unavailable (#6)






等待
你的OS是什么

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by kadeeq** [comment]
I told you multiple times. Send me a screenshot of your powershell with the command dir so i can check if your in the right file directory. Like this 
![grafik](https://user-images.githubusercontent.com/62156037/105466066-01cc1800-5c94-11eb-9859-7ebab7397399.png)

**Comment by kadeeq** [comment]
Also I think you have the python file (ProjectX.py) on a usb? I am not sure if that works. Another thing you can try is not opening the file via windows powershell but rather through the "cmd"
![grafik](https://user-images.githubusercontent.com/62156037/105466380-6be4bd00-5c94-11eb-8429-cd7271d835f1.png)

**Comment by hujihan** [comment]
O sorry，I use QQemail reply，so you can't see the screenshot，sorry！！
This is my screenshot
![QQ截图20210122163130](https://user-images.githubusercontent.com/46958243/105466623-684d3800-5c8c-11eb-971a-be3b10668dba.png)

**Comment by kadeeq** [comment]
is your python command working correctly?

**Comment by hujihan** [comment]
yes normal

**Comment by kadeeq** [comment]
ahh i have an idea:
please provide a screenshot of the python command like this:
![grafik](https://user-images.githubusercontent.com/62156037/105467219-aac74280-5c95-11eb-92fd-7595b321e6f1.png)

**Comment by kadeeq** [comment]
and i dont think it is beacause of usb stick

**Comment by kadeeq** [comment]
and do you have multiple python versions installed?

**Comment by hujihan** [comment]
![QQ截图20210122164759](https://user-images.githubusercontent.com/46958243/105468257-b2cfb400-5c8e-11eb-9580-5680340b942b.png)
Yes, I have two Python installed，And I found that when I typed Python in CMD, the Microsoft store would pop up，I have solved this problem

**Comment by kadeeq** [comment]
ok i think i know the problem
your python is 64 bit
im gonna add a 64bit version ok just wait a few minutes

**Comment by hujihan** [comment]
So that's the problem

**Comment by hujihan** [comment]
I run "Python" again ProjectX.py ”Reaction after
![QQ截图20210122165510](https://user-images.githubusercontent.com/46958243/105469207-cdeef380-5c8f-11eb-9f92-b927924bdcd0.png)

**Comment by kadeeq** [comment]
i think so because the program utilizes the win32gui module which is somewhat scuffed for 64 bit python. You can now try to redownload the ProjectX.py file and execute it again

**Comment by hujihan** [comment]
OK

**Comment by kadeeq** [comment]
also i dont think using the version from ms store works as i dont think it added to PATH

**Comment by hujihan** [comment]
Unfortunately, there was no response

**Comment by kadeeq** [comment]
no error nothing?

**Comment by hujihan** [comment]
![image](https://user-images.githubusercontent.com/46958243/105469966-e27fbb80-5c90-11eb-9763-5fdb655c65b9.png)
he sey ：“The connection attempt failed because the connecting party did not reply correctly after a period of time or the connected host did not respond.”

**Comment by hujihan** [comment]
Does this thing need to be connected to the Internet?

**Comment by hujihan** [comment]
Maybe I'm in China?

**Comment by hujihan** [comment]
`Traceback (most recent call last):
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接 的主机没有反应，连接尝试失败。', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ProjectX.py", line 12, in <module>
    response = requests.get( offsets ).json()
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HJH\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None))`

**Comment by hujihan** [comment]
I think you should delete obtain code for offset,Maybe it will be better

**Comment by kadeeq** [comment]
oh ok yeah it needs to be because it downloads the memory adresses from from github lmao
your firewall seems to be blocking the connection
i can send you a file with the momentarily correct offsets but this way the cheat will not automatically update itself and thus you need to replace the offsets everytime there is a new csgo update

**Comment by kadeeq** [comment]
try the chinaversion.py file

**Comment by hujihan** [comment]
yse!!!bro! It worked！！！
![QQ图片20210122173532](https://user-images.githubusercontent.com/46958243/105473594-32608180-5c95-11eb-8ccb-f0798251bf53.png)

**Comment by kadeeq** [comment]
nice :DDDD

**Comment by kadeeq** [comment]
ok the problem now is that it wont work the next time csgo has an update because the offsets may change
im gonna upload a new version for u and another offsetschina.json file which every time csgo has an update you need to paste into the offsets folder

**Comment by hujihan** [comment]
ok

**Comment by hujihan** [comment]
emmmm I don't quite understand what triggerbot and FOV mean They can't be translated can you explain what's the use

**Comment by kadeeq** [comment]
sure FOV changes your field of fov so how much you can see on your screen (try something like fov 120 and you will see what i mean) and triggerbot causes the cheat to shoot for you if press the triggerkey and your crosshair is on the enemy. This helps your reaction time by alot. Just try it out in an offline game with bots. The aimbot fov value configures how close your crosshair needs to be to the enemies head for the aimbot to activate. GLHF

**Comment by hujihan** [comment]
How to input FOV value, such as FOV 120，I pressed the number key on the keyboard many times, but it didn't respondQAQ，It prompts me to use different aimbot values
